// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ9eGHW6c_tt7L6PDuP9RO0cebHXzx6UM',
    appId: '1:388054230572:web:29505819a4c93324e29389',
    messagingSenderId: '388054230572',
    projectId: 'mindcare-flutter-app',
    authDomain: 'mindcare-flutter-app.firebaseapp.com',
    storageBucket: 'mindcare-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVCvaRPlpEDg4NsnaQ8hFUIpMaIUZ3ryY',
    appId: '1:388054230572:android:41a8922874baf0f7e29389',
    messagingSenderId: '388054230572',
    projectId: 'mindcare-flutter-app',
    storageBucket: 'mindcare-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDhN1_rW4VkpyeW8voIcWdf0f70mEW1Xs',
    appId: '1:388054230572:ios:716db404a8daf07fe29389',
    messagingSenderId: '388054230572',
    projectId: 'mindcare-flutter-app',
    storageBucket: 'mindcare-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.mindcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDhN1_rW4VkpyeW8voIcWdf0f70mEW1Xs',
    appId: '1:388054230572:ios:716db404a8daf07fe29389',
    messagingSenderId: '388054230572',
    projectId: 'mindcare-flutter-app',
    storageBucket: 'mindcare-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.mindcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ9eGHW6c_tt7L6PDuP9RO0cebHXzx6UM',
    appId: '1:388054230572:web:8d2f0eef58df4b2fe29389',
    messagingSenderId: '388054230572',
    projectId: 'mindcare-flutter-app',
    authDomain: 'mindcare-flutter-app.firebaseapp.com',
    storageBucket: 'mindcare-flutter-app.firebasestorage.app',
  );
}
